Add support for getting managed instance status
spotinst/spotinst-sdk-go pull request #107
Opened 2021-01-30 03:19 UTC by tenyo

We are starting to use the spotinst-sdk-go for one of our projects and we needed some additional functionality for Managed Instances (currently, only the basic List, Read, Update, Delete functions are implemented).

This PR adds support for the Managed Instance Status API call which returns additional information from the cloud provider.

I tested it locally and it works as expected. There were no existing tests for this provider, so I haven't written a test for the new function.

2021-02-11 08:26 UTC, liranp requested changes
Thank you for your contribution, @tenyo. Could you please review my suggestions?

2021-02-11 08:26 UTC, liranp commented on service/managedinstance/providers/aws/aws.go
> +	ImageId      *string    `json:"imageId,omitempty"`
```suggestion
	ImageID      *string    `json:"imageId,omitempty"`
```

[Ref](https://github.com/golang/go/wiki/CodeReviewComments#initialisms).

2021-02-11 08:26 UTC, liranp commented on service/managedinstance/providers/aws/aws.go
> +	InstanceId   *string    `json:"instanceId,omitempty"`
```suggestion
	InstanceID   *string    `json:"instanceId,omitempty"`
```

[Ref](https://github.com/golang/go/wiki/CodeReviewComments#initialisms).

2021-02-11 08:26 UTC, liranp commented on service/managedinstance/providers/aws/aws.go
> +	PrivateIp    *string    `json:"privateIp,omitempty"`
```suggestion
	PrivateIP    *string    `json:"privateIp,omitempty"`
```

[Ref](https://github.com/golang/go/wiki/CodeReviewComments#initialisms).

2021-02-11 08:26 UTC, liranp commented on service/managedinstance/providers/aws/aws.go
> +	PublicIp     *string    `json:"publicIp,omitempty"`
```suggestion
	PublicIP     *string    `json:"publicIp,omitempty"`
```

[Ref](https://github.com/golang/go/wiki/CodeReviewComments#initialisms).

2021-02-11 14:04 UTC, tenyo commented
Thanks for the review, @liranp. I have fixed those.

2021-02-13 17:15 UTC, liranp approved these changes

2021-02-13 17:16 UTC, merged

2021-02-13 17:19 UTC, liranp commented
Released [v1.78.0](https://github.com/spotinst/spotinst-sdk-go/releases/tag/v1.78.0). Thank you for your contribution, @tenyo.