Wave APIs
spotinst/spotinst-sdk-go pull request #113
Opened 2021-03-01 15:25 UTC by thorsteinnth

Adds APIs for Wave clusters and Spark applications.

2021-03-01 20:00 UTC, liranp commented on service/wave/wave.go
> +	OceanClusterId          *string `json:"oceanClusterId,omitempty"`
```suggestion
	OceanClusterID          *string `json:"oceanClusterId,omitempty"`
```
[Ref.](https://github.com/golang/go/wiki/CodeReviewComments#initialisms)

2021-03-01 20:01 UTC, liranp commented on service/wave/wave.go
> +	Uid             *string           `json:"uid,omitempty"`
```suggestion
	UID             *string           `json:"uid,omitempty"`
```
[Ref.](https://github.com/golang/go/wiki/CodeReviewComments#initialisms)

2021-03-01 20:01 UTC, liranp commented on service/wave/wave.go
> +	ApplicationId     *string `json:"applicationId,omitempty"`
```suggestion
	ApplicationID     *string `json:"applicationId,omitempty"`
```
[Ref.](https://github.com/golang/go/wiki/CodeReviewComments#initialisms)

2021-03-01 20:03 UTC, liranp commented on service/wave/wave.go
> +		if input.ApplicationId != nil {
```suggestion
		if input.ApplicationID != nil {
```
[Ref.](https://github.com/golang/go/wiki/CodeReviewComments#initialisms)

2021-03-01 20:03 UTC, liranp commented on service/wave/wave.go
> +			r.Params.Set("applicationId", spotinst.StringValue(input.ApplicationId))
```suggestion
			r.Params.Set("applicationId", spotinst.StringValue(input.ApplicationID))
```
[Ref.](https://github.com/golang/go/wiki/CodeReviewComments#initialisms)

2021-03-01 20:05 UTC, liranp requested changes
@thorsteinnth Could you please review my suggestions? Thanks!

2021-03-03 14:13 UTC, thorsteinnth commented
> @thorsteinnth Could you please review my suggestions? Thanks!

Thanks @liranp - I have pushed fixes for your suggestions

2021-03-03 16:31 UTC, liranp approved these changes

2021-03-03 16:36 UTC, merged

2021-03-03 16:52 UTC, liranp commented
Released [v1.80.0](https://github.com/spotinst/spotinst-sdk-go/releases/tag/v1.80.0).