added tags parameter in azurev3
spotinst/spotinst-sdk-go pull request #247
Opened 2023-05-22 12:54 UTC by pripatra

_This is the default pull request template. You can customize it by adding a `pull_request_template.md` at the root of your repo or inside the `.github` folder._

# Jira Ticket

_Include a link to your Jira Ticket_
_Example: [JIRAISS-1234](https://spotinst.atlassian.net/browse/JIRAISS-1234)_

# Demo

_Please add a recording of the feature/bug fix in work. if you added new routes, the recording should show the request and response for each new/changed route_

# Checklist:
- [ ] I have filled relevant self assessment ([NodeJS](https://docs.google.com/forms/d/e/1FAIpQLSfl14u9AOBAmxVJ272tvO7XNuXE-EMvWaGcaRZalu1UAKB7RA/viewform), [Frontend](https://docs.google.com/forms/d/e/1FAIpQLSdiBPNKH81w_EkavihVL8Uwb0j7tP8PwJmLFYm2nCOQxz-1qw/viewform), [Backend](https://docs.google.com/forms/d/e/1FAIpQLSed_PsTJ5-XIWkFL6BSDE2AQRBVPmwc3PAmHZkUn-erzVI37Q/viewform?usp=sf_link))
- [ ] I have run ESlint on my changes and fixed all warnings and errors (**NodeJS & Frontend Services**)
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have validated all the requirements in the Jira task were answered
- [ ] I have all neccessary approvals for the design/mini design of this task
- [ ] I have approved the API changes and granular permission patterns (documentation subtask) (**For public services only**)

2023-05-22 15:10 UTC, chandra1-n commented on service/elastigroup/providers/azure/v3/azure.go
> +type Tag struct {
use Tags

2023-05-22 15:12 UTC, chandra1-n commented on service/elastigroup/providers/azure/v3/azure.go
>  // endregion
setKey and setValue functions are missing

2023-05-22 15:12 UTC, chandra1-n requested changes
please fix the review comments

2023-05-23 08:55 UTC, pripatra commented on service/elastigroup/providers/azure/v3/azure.go
> +	Tags                     []*Tag                    `json:"tags,omitempty"`
Done

2023-05-23 08:55 UTC, pripatra commented on service/elastigroup/providers/azure/v3/azure.go
> +type Tag struct {
Done

2023-05-23 09:10 UTC, chandra1-n approved these changes

2023-05-23 09:11 UTC, merged