Spotaut 18517 - Implemented Go Sdk for Verification Template
spotinst/spotinst-sdk-go pull request #298
Opened 2024-05-10 04:18 UTC by IGUDE2

_This is the default pull request template. You can customize it by adding a `pull_request_template.md` at the root of your repo or inside the `.github` folder._

# Jira Ticket

_Include a link to your Jira Ticket_
_Example: [JIRAISS-1234](https://spotinst.atlassian.net/browse/JIRAISS-1234)_

# Demo

_Please add a recording of the feature/bug fix in work. if you added new routes, the recording should show the request and response for each new/changed route_

# Checklist:
- [ ] I have filled relevant self assessment ([NodeJS](https://docs.google.com/forms/d/e/1FAIpQLSfl14u9AOBAmxVJ272tvO7XNuXE-EMvWaGcaRZalu1UAKB7RA/viewform), [Frontend](https://docs.google.com/forms/d/e/1FAIpQLSdiBPNKH81w_EkavihVL8Uwb0j7tP8PwJmLFYm2nCOQxz-1qw/viewform), [Backend](https://docs.google.com/forms/d/e/1FAIpQLSed_PsTJ5-XIWkFL6BSDE2AQRBVPmwc3PAmHZkUn-erzVI37Q/viewform?usp=sf_link))
- [ ] I have run ESlint on my changes and fixed all warnings and errors (**NodeJS & Frontend Services**)
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have validated all the requirements in the Jira task were answered
- [ ] I have all neccessary approvals for the design/mini design of this task
- [ ] I have approved the API changes and granular permission patterns (documentation subtask) (**For public services only**)

2024-05-10 14:20 UTC, chandra1-n commented on service/oceancd/verificationTemplate.go
> +	Web        *Web                `json:"web,omitempty"`
job object is missing

2024-05-11 07:31 UTC, chandra1-n commented on service/oceancd/verificationTemplate.go
> +	DryRun                *bool     `json:"dryRUn,omitempty"`
correct the dryRUn to dryRun

2024-05-11 07:32 UTC, chandra1-n commented on service/oceancd/verificationTemplate.go
> +	DataDog    *DataDogProvider    `json:"dataDog,omitempty"`
corect dataDog to datadog

2024-05-11 07:35 UTC, chandra1-n commented on service/oceancd/verificationTemplate.go
> +	MetricStat *MetricStat `json:"MetricStat,omitempty"`
modify to metricStat

2024-05-11 07:35 UTC, chandra1-n commented on service/oceancd/verificationTemplate.go
> +	Period     *int        `json:"duration,omitempty"`
modify to period

2024-05-11 07:36 UTC, chandra1-n commented on service/oceancd/verificationTemplate.go
> +	Metric *Metric `json:"address,omitempty"`
modify to metric

2024-05-11 07:37 UTC, chandra1-n commented on service/oceancd/verificationTemplate.go
> +	NameSpace  *string       `json:"nameSpace,omitempty"`
shouldn't be camel-case

2024-05-11 07:38 UTC, chandra1-n commented on service/oceancd/verificationTemplate.go
> +	Interval        *string       `json:"address,omitempty"`
modify to interval

2024-05-11 07:40 UTC, chandra1-n commented on service/oceancd/verificationTemplate.go
> +	TimeoutSeconds *int       `json:"TimeoutSeconds,omitempty"`
modify to timeoutSeconds

2024-05-11 08:23 UTC, chandra1-n requested changes
please fix the review comments

2024-05-13 03:06 UTC, IGUDE2 commented on service/oceancd/verificationTemplate.go
> +	Web        *Web                `json:"web,omitempty"`
Added Job Object and definations

2024-05-13 03:06 UTC, IGUDE2 commented on service/oceancd/verificationTemplate.go
> +type Provider struct {
Restested with the Provider

2024-05-13 03:06 UTC, IGUDE2 commented on service/oceancd/verificationTemplate.go
> +	DryRun                *bool     `json:"dryRUn,omitempty"`
corrected

2024-05-13 03:06 UTC, IGUDE2 commented on service/oceancd/verificationTemplate.go
> +	DataDog    *DataDogProvider    `json:"dataDog,omitempty"`
corrected

2024-05-13 03:06 UTC, IGUDE2 commented on service/oceancd/verificationTemplate.go
> +	MetricStat *MetricStat `json:"MetricStat,omitempty"`
corrected

2024-05-13 03:07 UTC, IGUDE2 commented on service/oceancd/verificationTemplate.go
> +	Period     *int        `json:"duration,omitempty"`
modified

2024-05-13 03:07 UTC, IGUDE2 commented on service/oceancd/verificationTemplate.go
> +	Metric *Metric `json:"address,omitempty"`
modified

2024-05-13 03:07 UTC, IGUDE2 commented on service/oceancd/verificationTemplate.go
> +	NameSpace  *string       `json:"nameSpace,omitempty"`
changed

2024-05-13 03:07 UTC, IGUDE2 commented on service/oceancd/verificationTemplate.go
> +	Interval        *string       `json:"address,omitempty"`
modified

2024-05-13 03:07 UTC, IGUDE2 commented on service/oceancd/verificationTemplate.go
> +	TimeoutSeconds *int       `json:"TimeoutSeconds,omitempty"`
modified

2024-05-13 08:21 UTC, chandra1-n approved these changes

2024-05-13 08:22 UTC, merged